---
driver:
  name: rackspace
  flavor_id: performance1-4
  rackspace_region: DFW
  require_chef_omnibus: latest
  server_name: ci-<%= ENV['CIRCLE_PROJECT_REPONAME'] %>-<%= ENV['CIRCLE_BUILD_NUM'] %>-<%= require 'securerandom'; SecureRandom.hex(6) %>
  wait_for: 1200
