---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80,   host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443,   host: 8443, auto_correct: true}]
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  environments_path: test/integration/environments
  require_chef_omnibus: 11.16.4
  attributes:
    magentostack:
      web:
        http_port: '8080'
        https_port: '8443'
    
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"

platforms:
  # Leaving Ubuntu out until Phase 2
  # - name: ubuntu-12.04
  #   run_list:
  #   - recipe[apt]
  # - name: ubuntu-14.04
  #   run_list:
  #   - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    provisioner:
        client_rb:
          environment: default_single
    run_list:
      - recipe[wrapper::default]

  - name: default-expanded
    provisioner:
        client_rb:
          environment: default_expanded
    run_list:
      - recipe[wrapper::default_expanded]
