---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80,   host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443,   host: 8443, auto_correct: true}]
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"
    mysql-multi:
      master: '127.0.0.1'
    magentostack:
      web:
        domain: 'localhost'
      config:
        secure_base_url: 'https://localhost:8443/'
        url: 'http://localhost:8080/'

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[wrapper::default]

  - name: default-expanded
    run_list:
      - recipe[wrapper::default_expanded]
