---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 8181,   host: 8181, auto_correct: true}]
  - ["forwarded_port", {guest: 8080,   host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 8443,   host: 8443, auto_correct: true}]
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  environments_path: test/integration/environments
  require_chef_omnibus: 12.4.1
  attributes:
    apache:
      mod_fastcgi:
        download_url: 'https://s3.amazonaws.com/rackspace-mirrors/www.fastcgi.com/fastcgi.tar.gz'
    magentostack:
      download_url: 'https://s3.amazonaws.com/rackspace-mirrors/magento/magento-1.9.1.1.tar.gz'
      checksum: 'e04c75f1be09844b92f5bbae04e417961447908000c591a29471b8634440dd1b'
      varnish:
        secret: "9a160c7a-22f2-45a7-b5ab-ec32dc060714\n"
        listen_port: 8181
      web:
        http_port: '8080'
        https_port: '8443'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    mysql:
      server_root_password: "randompass"
      server_repl_password: "randompass"
      server_debian_password: "randompass"
    holland:
      password: "randompass"

platforms:
  # Leaving Ubuntu out until Phase 2
  # - name: ubuntu-12.04
  #   run_list:
  #   - recipe[apt]
  # - name: ubuntu-14.04
  #   run_list:
  #   - recipe[apt]
  - name: centos-6.7
    run_list:
    - recipe[yum]

# NB: Every build will specify 'community' or 'enterprise' edition, but all
# other test suite attributes are assumed to be php55 and git with a single
# redis instance locally on the same server, when not specified.
suites:
  - name: community
    provisioner:
        client_rb:
          environment: default_single
    run_list:
      - recipe[wrapper::default]

<% if ENV['RACKSPACE_MAGENTOSTACK_DEPLOYKEY'] %>
  - name: enterprise
    run_list:
      - recipe[wrapper::default]
    attributes:
      magentostack:
        flavor: 'enterprise'
        install_method: 'git'
        git_repository: 'git@github.com:rackerlabs/enterprise-magento-chef-demo.git'
        git_revision: 'v1.14.1.0'
        git_deploykey: <%= ENV['RACKSPACE_MAGENTOSTACK_DEPLOYKEY'] %>

<% end %>
<% if ENV['MAGENTOSTACK_CLOUDFILES'] && ENV['RACKSPACE_API_KEY'] %>
# we have disabled this for now. there's no deployments using this, and we're not
# really even sure it has value. We only used at the start before we had git.
  - name: enterprise-cloudfiles
    run_list:
      - recipe[wrapper::default]
    attributes:
      rackspace:
        cloud_credentials:
          username: <%= ENV['RACKSPACE_USERNAME'] %>
          api_key: <%= ENV['RACKSPACE_API_KEY'] %>
      magentostack:
        flavor: 'enterprise'
        install_method: 'cloudfiles'
        download_file: 'magento-ee-1.14.0.1.tar.gz'
        checksum: '1e3657778ecac9f1d0470326afdaddad36a88e2fa58b650749eb35d446e71868'
<% end %>
<% if ENV['RACKSPACE_MAGENTOSTACK_SVNTOKEN'] %>
  - name: enterprise-svn
    run_list:
      - recipe[wrapper::default]
    attributes:
      magentostack:
        flavor: 'enterprise'
        install_method: 'svn'
        svn_username: 'devopsbot'
        svn_password: <%= ENV['RACKSPACE_MAGENTOSTACK_SVNTOKEN'] %>
        svn_repository: 'https://github.com/rackerlabs/enterprise-magento-chef-demo/trunk'
        svn_revision: HEAD
<% end %>
